### ISSUE TITLE
[Feature] Support asynchronous options.url function

### ISSUE THREAD

**Issue by xiata** [sanity-io/sanity-plugin-seo-pane#3]
Unfortunately, it is not always possible to synchronously resolve document URLs, which `options.url` expects.

In my project, a document's url is a combination of a url slug and a reference to a route prefix, so it needs to perform a `client.fetch` to get part of the URL path, which unfortunately leads to a promise which isn't handled well elsewhere outside the SeoPane component.

Any plans on support, or should I just fork and pr now?

**Comment by SimeonGriggs** [comment]
Yes that could be possible. 

Additionally I'd like to support functions for keywords too because they're not always stored on the document you're editing either. 

Stay tuned!

**Comment by xiata** [comment]
PR: https://github.com/SimeonGriggs/sanity-plugin-seo-pane/pull/4

**Comment by SimeonGriggs** [comment]
Merged!
