### ISSUE TITLE
Update to v3

### ISSUE THREAD

**Issue by Designer023** [sanity-io/sanity-plugin-seo-pane#8]
Hi, 

Thanks for the great plugin. Do you have any plans to migrate this to V3 or create a V3 version?

If not I will try and have a go myself when I have some free time 👍 

Cheers

**Comment by radscheit** [comment]
> Hi,
> 
> Thanks for the great plugin. Do you have any plans to migrate this to V3 or create a V3 version?
> 
> If not I will try and have a go myself when I have some free time 👍
> 
> Cheers

Did you find some free time? @Designer023

**Comment by Designer023** [comment]
@radscheit Sadly I haven't had time yet!

**Comment by Designer023** [comment]
This now works with V3
