### ISSUE TITLE
breaking yoastseo dependency

### ISSUE THREAD

**Issue by radscheit** [sanity-io/sanity-plugin-seo-pane#9]
After adding the package to a v3 Studio I got a breaking error:

`Failed to resolve entry for package "yoastseo". The package may have incorrect main/module/exports specified in its package.json.`

**Comment by radscheit** [comment]
> After adding the package to a v3 Studio I got a breaking error:
> 
> `Failed to resolve entry for package "yoastseo". The package may have incorrect main/module/exports specified in its package.json.`

Possibly related to https://github.com/Yoast/wordpress-seo/pull/19361

**Comment by Designer023** [comment]
The same issue was on [another Sanity plugin](https://github.com/LiamMartens/sanity-plugin-seo-tools/issues/64) which was just fixed by bumping the `yoastseo` package to `1.91.1`.

I would suggest that the same fix would work here

**Comment by radscheit** [comment]
@Designer023 See closed PR https://github.com/sanity-io/sanity-plugin-seo-pane/pull/10
